// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAteTttftXB7ZHxzjqr0QAC6W2e96_XSUk',
    appId: '1:372667235313:web:a63eb563ea300ca6336250',
    messagingSenderId: '372667235313',
    projectId: 'survey-cam-c103a',
    authDomain: 'survey-cam-c103a.firebaseapp.com',
    storageBucket: 'survey-cam-c103a.appspot.com',
    measurementId: 'G-557HJFEMCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jWDg8TlRaoNRo6vDSKaHVV6Kpm6fTTI',
    appId: '1:372667235313:android:7752a0c79f331997336250',
    messagingSenderId: '372667235313',
    projectId: 'survey-cam-c103a',
    storageBucket: 'survey-cam-c103a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGTtKOnwrRFpI0xyBbmudiHQ4hOkmJbp4',
    appId: '1:372667235313:ios:9b3e39268b1200fb336250',
    messagingSenderId: '372667235313',
    projectId: 'survey-cam-c103a',
    storageBucket: 'survey-cam-c103a.appspot.com',
    iosBundleId: 'com.example.surveyCap',
  );
}
